version: "2"
services:
  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - app
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf

  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes_from:
      - app
    depends_on:
      - db

  app:
    build: ./app
    environment:
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_HOST: "db:3306"
    volumes:
      - /usr/local/nginx/html
      - ./app/wp-config.php:/usr/local/nginx/html/wp-config.php

  db:
    image: mysql:5.7.18
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wp_user"
      MYSQL_PASSWORD: "hogehoge"
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql

volumes:
    db-data:
